
import PanchangaClient from '@/components/panchanga/PanchangaClient';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Panchang Calendar Service | Shivbodh Trust',
  description: "An embeddable Panchang calendar widget service by Shivbodh Trust, providing detailed daily astrological information generated by Google Gemini.",
};

export default function PanchangaPage() {
  return <PanchangaClient />;
}
