
export const dwarakaPhotoGallery = [
    { id: 'dwaraka-photo-1', date: '2024-07-18', title: 'The Majestic Dwarakadhish Temple', description: 'The grand Dwarakadhish Temple standing tall against the sky.', alt: 'Dwarakadhish Temple', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'temple gopuram' },
    { id: 'dwaraka-photo-2', date: '2024-07-17', title: "An Acharya's Discourse", description: 'The Shankaracharya of Dwaraka delivering a profound discourse.', alt: 'Acharya giving a discourse', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'acharya discourse' },
    { id: 'dwaraka-photo-3', date: '2024-07-16', title: 'Peaceful Gomti Ghat', description: 'The serene steps of the Gomti Ghat leading to the river.', alt: 'Gomti Ghat', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'river steps' },
    { id: 'dwaraka-photo-4', date: '2024-07-15', title: 'Ancient Vedic Scriptures', description: 'A collection of ancient scriptures preserved at the Peetham.', alt: 'Ancient scriptures', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'ancient manuscript' },
    { id: 'dwaraka-photo-5', date: '2023-09-07', title: 'Janmashtami Celebrations 2023', description: 'Devotees celebrating the birth of Lord Krishna at the Peetham.', alt: 'Devotees celebrating Janmashtami', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'festival celebration' },
    { id: 'dwaraka-photo-6', date: '2022-06-10', title: 'Peetham Entrance Archway', description: 'The beautifully carved entrance to the Dwaraka Sharada Peetham.', alt: 'Entrance of Dwaraka Peetham', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'temple entrance' },
    { id: 'dwaraka-photo-10', date: '2019-08-24', title: 'Janmashtami 2019', description: 'Archival image of Janmashtami celebrations from 2019.', alt: 'Janmashtami festival in 2019', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'festival procession' },
    { id: 'dwaraka-photo-7', date: '2016-08-25', title: 'Janmashtami 2016', description: 'An archival image of Janmashtami celebrations from 2016.', alt: 'Janmashtami festival in 2016', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'festival lights' },
    { id: 'dwaraka-photo-11', date: '2014-07-12', title: 'Guru Purnima 2014', description: 'Devotees gather to honor the Guru on Purnima in 2014.', alt: 'Guru Purnima 2014', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'guru blessings' },
    { id: 'dwaraka-photo-8', date: '2013-02-10', title: 'Devotee Gathering 2013', description: 'Devotees gather for a special discourse in the winter of 2013.', alt: 'Devotees at a discourse', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'spiritual gathering' },
    { id: 'dwaraka-photo-12', date: '2011-11-11', title: 'Gita Jayanti 2011', description: 'A celebration of Gita Jayanti at the Peetham.', alt: 'Gita Jayanti 2011', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'scripture reading' },
    { id: 'dwaraka-photo-9', date: '2010-11-05', title: 'Diwali Aarti 2010', description: 'The main shrine during the evening aarti on Diwali in 2010.', alt: 'Temple aarti during Diwali', src: 'https://placehold.co/600x400.png', thumbnailUrl: 'https://placehold.co/400x300.png', aiHint: 'diwali aarti' },
];
