
export const jyotirmathPhotoGallery = [
    { id: 'jyotirmath-photo-1', date: '2024-07-18', title: 'Snow-Capped Himalayan Peaks', description: 'The majestic beauty of the Himalayan mountains surrounding Jyotirmath.', alt: 'Himalayan mountains', src: 'https://placehold.co/400x300.png', aiHint: 'himalayan mountains' },
    { id: 'jyotirmath-photo-2', date: '2024-07-17', title: 'The Sacred Badrinath Shrine', description: 'A view of the sacred Badrinath Temple shrine.', alt: 'Badrinath Temple shrine', src: 'https://placehold.co/400x300.png', aiHint: 'badrinath temple' },
    { id: 'jyotirmath-photo-3', date: '2024-07-16', title: 'A Sadhu in Meditation', description: 'A Sadhu meditates in a cave, embodying the spirit of the Himalayas.', alt: 'A sadhu meditating in a cave', src: 'https://placehold.co/400x300.png', aiHint: 'sadhu meditation' },
    { id: 'jyotirmath-photo-4', date: '2024-07-15', title: 'The Alaknanda River Valley', description: 'The pristine and beautiful valley of the Alaknanda river.', alt: 'The Alaknanda river valley', src: 'https://placehold.co/400x300.png', aiHint: 'river valley' },
    { id: 'jyotirmath-photo-5', date: '2023-05-15', title: 'Badrinath Temple Opening 2023', description: 'The gates of the Badrinath shrine opening for the season in 2023.', alt: 'Badrinath temple doors opening', src: 'https://placehold.co/400x300.png', aiHint: 'temple opening' },
    { id: 'jyotirmath-photo-6', date: '2022-10-20', title: 'Autumn in Jyotirmath', description: 'The vibrant autumn colors in the town of Jyotirmath.', alt: 'Autumn colors in the Himalayas', src: 'https://placehold.co/400x300.png', aiHint: 'autumn mountains' },
    { id: 'jyotirmath-photo-10', date: '2019-06-15', title: 'Himalayan Flowers', description: 'Wildflowers blooming in the Himalayan meadows during summer 2019.', alt: 'Himalayan wildflowers', src: 'https://placehold.co/400x300.png', aiHint: 'mountain flowers' },
    { id: 'jyotirmath-photo-7', date: '2015-06-01', title: 'Himalayan Summer 2015', description: 'A view of the lush green Himalayas during the summer of 2015.', alt: 'Summer in the Himalayas', src: 'https://placehold.co/400x300.png', aiHint: 'summer mountains' },
    { id: 'jyotirmath-photo-11', date: '2014-09-01', title: 'View of Neelkanth Peak', description: 'A clear day view of the Neelkanth peak from 2014.', alt: 'Neelkanth Peak', src: 'https://placehold.co/400x300.png', aiHint: 'snowy mountain' },
    { id: 'jyotirmath-photo-8', date: '2013-06-20', title: 'Monsoon Clouds over Jyotirmath', description: 'Dramatic monsoon clouds gathering over the mountains in 2013.', alt: 'Monsoon clouds in the mountains', src: 'https://placehold.co/400x300.png', aiHint: 'monsoon clouds' },
    { id: 'jyotirmath-photo-12', date: '2011-05-10', title: 'Pilgrims at Badrinath', description: 'A group of pilgrims at the Badrinath temple in 2011.', alt: 'Pilgrims at temple', src: 'https://placehold.co/400x300.png', aiHint: 'pilgrims temple' },
    { id: 'jyotirmath-photo-9', date: '2010-09-10', title: 'Ancient Jyotirmath Temple', description: 'A photograph of the ancient temple at Jyotirmath from 2010.', alt: 'Old temple in Jyotirmath', src: 'https://placehold.co/400x300.png', aiHint: 'ancient temple' },
];
