
export const puriPhotoGallery = [
    { id: 'puri-photo-1', date: '2024-07-18', title: 'Lord Jagannath Temple, Puri', description: 'The iconic Jagannath Temple, a major pilgrimage destination.', alt: 'Jagannath Temple, Puri', src: 'https://source.unsplash.com/600x400/?jagannath,temple', thumbnailUrl: 'https://source.unsplash.com/400x300/?jagannath,temple', aiHint: 'jagannath temple' },
    { id: 'puri-photo-2', date: '2024-07-07', title: 'Grandeur of Ratha Yatra', description: 'The chariots during the world-famous Ratha Yatra festival.', alt: 'Ratha Yatra festival', src: 'https://source.unsplash.com/600x400/?chariot,festival', thumbnailUrl: 'https://source.unsplash.com/400x300/?chariot,festival', aiHint: 'chariot festival' },
    { id: 'puri-photo-3', date: '2024-07-16', title: 'Shankaracharya Addresses a Gathering', description: 'The Shankaracharya of Puri delivering a speech at a spiritual conference.', alt: 'Shankaracharya giving a speech', src: 'https://source.unsplash.com/600x400/?acharya,speech', thumbnailUrl: 'https://source.unsplash.com/400x300/?acharya,speech', aiHint: 'acharya speech' },
    { id: 'puri-photo-4', date: '2024-07-15', title: 'Devotees at the Peetham', description: 'A spiritual gathering of devotees at the Peetham.', alt: 'A spiritual gathering at the Peetham', src: 'https://source.unsplash.com/600x400/?devotees,gathering', thumbnailUrl: 'https://source.unsplash.com/400x300/?devotees,gathering', aiHint: 'devotees gathering' },
    { id: 'puri-photo-5', date: '2023-06-20', title: 'Ratha Yatra 2023', description: 'An archival photo of the grand chariots from the 2023 Ratha Yatra.', alt: 'Ratha Yatra 2023', src: 'https://source.unsplash.com/600x400/?festival,chariot', thumbnailUrl: 'https://source.unsplash.com/400x300/?festival,chariot', aiHint: 'festival chariot' },
    { id: 'puri-photo-6', date: '2022-10-05', title: 'Govardhan Math Entrance', description: 'The serene entrance to the Govardhan Math in Puri.', alt: 'Entrance to Govardhan Math', src: 'https://source.unsplash.com/600x400/?monastery,entrance', thumbnailUrl: 'https://source.unsplash.com/400x300/?monastery,entrance', aiHint: 'monastery entrance' },
    { id: 'puri-photo-10', date: '2019-02-15', title: 'Vedic Chanting Session', description: 'A session of Rig Veda chanting at the Peetham in 2019.', alt: 'Vedic chanting', src: 'https://source.unsplash.com/600x400/?vedic,chanting', thumbnailUrl: 'https://source.unsplash.com/400x300/?vedic,chanting', aiHint: 'vedic chanting' },
    { id: 'puri-photo-7', date: '2015-07-18', title: 'Ratha Yatra 2015', description: 'A look back at the Ratha Yatra from 2015.', alt: 'Ratha Yatra 2015', src: 'https://source.unsplash.com/600x400/?festival,parade', thumbnailUrl: 'https://source.unsplash.com/400x300/?festival,parade', aiHint: 'festival parade' },
    { id: 'puri-photo-11', date: '2014-01-20', title: 'Peetham Scholars', description: 'Scholars of the Govardhan Math in discussion, from 2014.', alt: 'Scholars in discussion', src: 'https://source.unsplash.com/600x400/?scholars,discussion', thumbnailUrl: 'https://source.unsplash.com/400x300/?scholars,discussion', aiHint: 'scholars discussion' },
    { id: 'puri-photo-8', date: '2012-04-01', title: 'Puri Sea Beach', description: 'The holy sea beach at Puri in 2012.', alt: 'Puri sea beach', src: 'https://source.unsplash.com/600x400/?sea,beach', thumbnailUrl: 'https://source.unsplash.com/400x300/?sea,beach', aiHint: 'sea beach' },
    { id: 'puri-photo-12', date: '2011-03-03', title: 'Holi Celebrations 2011', description: 'Devotees celebrating the festival of Holi at the Peetham.', alt: 'Holi festival celebrations', src: 'https://source.unsplash.com/600x400/?holi,festival', thumbnailUrl: 'https://source.unsplash.com/400x300/?holi,festival', aiHint: 'holi festival' },
    { id: 'puri-photo-9', date: '2010-01-26', title: 'Saraswati Puja 2010', description: 'Archival image of Saraswati Puja celebrations at the Peetham.', alt: 'Saraswati Puja ceremony', src: 'https://source.unsplash.com/600x400/?goddess,statue', thumbnailUrl: 'https://source.unsplash.com/400x300/?goddess,statue', aiHint: 'goddess statue' },
];
